# to build
# $ docker build -f Dockerfile_ubuntu22.04 .
#

FROM ubuntu:22.04

ARG SDPA_DD_VER="7.1.3"

RUN apt -y update
RUN apt -y upgrade
RUN apt install -y sudo
RUN apt install -y tzdata
# set your timezone
ENV TZ Asia/Tokyo
RUN echo "${TZ}" > /etc/timezone \
  && rm /etc/localtime \
  && ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
  && dpkg-reconfigure -f noninteractive tzdata

RUN apt install -y build-essential g++
RUN apt install -y autotools-dev automake libtool
RUN apt install -y git wget time
RUN apt install -y ng-common ng-cjk

ARG DOCKER_UID=1000
ARG DOCKER_USER=docker
ARG DOCKER_PASSWORD=docker
RUN useradd -u $DOCKER_UID -m $DOCKER_USER --shell /bin/bash && echo "$DOCKER_USER:$DOCKER_PASSWORD" | chpasswd && echo "$DOCKER_USER ALL=(ALL) ALL" >> /etc/sudoers
USER ${DOCKER_USER}

RUN cd /home/$DOCKER_USER && echo "cd /home/$DOCKER_USER" >> .bashrc
RUN cd /home/$DOCKER_USER && git https://github.com/nakatamaho/sdpa-dd.git
RUN cd /home/$DOCKER_USER && cd sdpa-dd; aclocal ; autoconf ; automake --add-missing ; ./configure ; make dist
RUN cd /home/$DOCKER_USER && mkdir /home/$DOCKER_USER/tmp
RUN cd /home/$DOCKER_USER/tmp && tar xvf sdpa-dd-${SDPA_DD_VER}.tar.gz
RUN cd /home/$DOCKER_USER/tmp/sdpa-dd-${SDPA_DD_VER} && ./configure ; make

